apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: mongo
    type: database
spec:
  containers:
    - name: mongo-container
      image: mongo
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user

        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password