apiVersion: v1
kind: Pod
metadata: 
  name: voting-app-pod
  labels:
    app: voting-app
    type: backend
spec:
  containers:
    - name: voting-container
      image: abduldanish/votingapp:3.0
      ports:
        - containerPort: 8020
      env:
        - name: VOTE_RESULT_API_HOST
          value: voting-result-service:8030

        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-host

        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-port

        - name: MONGO_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: mongo-db

        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password