apiVersion: v1
kind: Pod
metadata: 
  name: voting-result-app
  labels:
    app: voting-result
    type: backend
spec:
  containers:
     - name: voting-result-container
       image: abduldanish/voting_result_app:2.0
       ports:
         - containerPort: 8030
       env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-host

        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-port

        - name: MONGO_DATABASE
          valueFrom: 
            configMapKeyRef:
              name: mongo-config
              key: mongo-db

        - name: MONGO_USER
          valueFrom:
            secretKeyRef:  
              name: mongo-secret
              key: mongo-user

        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password